tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "stripe/stripe-cli"
tap "supabase/tap"
brew "python@3.9"
brew "glib"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "gobject-introspection"
brew "harfbuzz"
brew "ffmpeg"
brew "gh"
brew "hostess"
brew "imagemagick"
brew "libfido2"
brew "python@3.10"
brew "mackup"
brew "openjdk"
brew "maven"
brew "mysql", restart_service: true
brew "nghttp2"
brew "node@12"
brew "nvm"
brew "subversion"
brew "youtube-dl"
brew "stripe/stripe-cli/stripe"
brew "supabase/tap/supabase"
cask "adobe-creative-cloud"
cask "appcleaner"
cask "apppolice"
cask "audacity"
cask "bitwarden"
cask "calibre"
cask "centered"
cask "clipy"
cask "daisydisk"
cask "discord"
cask "drivethrurpg"
cask "firefox"
cask "font-ia-writer-duospace"
cask "font-lato"
cask "font-source-code-pro"
cask "font-source-sans-pro"
cask "google-chrome"
cask "handbrake"
cask "itch"
cask "itsycal"
cask "local"
cask "obs"
cask "obs-ndi"
cask "obsidian"
cask "plex-media-server"
cask "raycast"
cask "scrivener"
cask "sequel-ace"
cask "skype"
cask "slack"
cask "spotify"
cask "steam"
cask "the-unarchiver"
cask "transmission"
cask "ubersicht"
cask "visual-studio-code"
cask "vlc"
cask "warp"
cask "workflowy"
cask "zoom"
mas "DaVinci Resolve", id: 571213070
mas "GarageBand", id: 682658836
mas "HP Smart", id: 1474276998
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kiwi for Gmail", id: 986304488
mas "Mini Motorways", id: 1456188526
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
